import { DamageType, EncounterType, Rarity } from "@/models/enums";
import type { GuildRaidResult, Raid } from "@/models/types";
import type { MemberStatsPerSeason } from "@/commands/guild/memberStatsBySeason";

export const RaidResultFixture: Raid[] = [
    {
        userId: "testUser1",
        tier: 0,
        set: 0,
        type: "TervigonLeviathan",
        damageDealt: 18000,
        startedOn: 1742984513,
        encounterIndexz: 0,
        remainingHp: 0,
        maxHp: 0,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "",
        rarity: Rarity.COMMON,
        damageType: DamageType.BATTLE,
        completedOn: 0,
        heroDetails: [],
        machineOfWarDetails: { unitId: "", power: 0 },
        globalConfigHash: "",
    },
    {
        userId: "testUser22",
        tier: 0,
        set: 1,
        type: "HiveTyrantLeviathan",
        damageDealt: 27000,
        startedOn: 1742984574,
        encounterIndexz: 0,
        remainingHp: 0,
        maxHp: 0,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "",
        rarity: Rarity.COMMON,
        damageType: DamageType.BATTLE,
        completedOn: 0,
        heroDetails: [],
        machineOfWarDetails: { unitId: "", power: 0 },

        globalConfigHash: "",
    },
    {
        userId: "testUser22",
        tier: 0,
        set: 2,
        type: "HiveTyrantGorgon",
        damageDealt: 36000,
        startedOn: 1742984633,
        encounterIndexz: 0,
        remainingHp: 0,
        maxHp: 0,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "",
        rarity: Rarity.COMMON,
        damageType: DamageType.BATTLE,
        completedOn: 0,
        heroDetails: [],
        machineOfWarDetails: { unitId: "", power: 0 },

        globalConfigHash: "",
    },
    {
        userId: "testUser24",
        tier: 0,
        set: 3,
        type: "ScreamerKiller",
        damageDealt: 91135,
        startedOn: 1742985806,
        encounterIndexz: 0,
        remainingHp: 0,
        maxHp: 0,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "",
        rarity: Rarity.COMMON,
        damageType: DamageType.BATTLE,
        completedOn: 0,
        heroDetails: [],
        machineOfWarDetails: { unitId: "", power: 0 },

        globalConfigHash: "",
    },
    {
        userId: "testUser32",
        tier: 0,
        set: 3,
        type: "ScreamerKiller",
        startedOn: 1742986285,
        damageDealt: 27800,
        encounterIndexz: 0,
        remainingHp: 0,
        maxHp: 0,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "",
        rarity: Rarity.COMMON,
        damageType: DamageType.BATTLE,
        completedOn: 0,
        heroDetails: [],
        machineOfWarDetails: { unitId: "", power: 0 },

        globalConfigHash: "",
    },
];

export const GuildRaidResultFixture: GuildRaidResult[] = [
    {
        username: "testUser1",
        totalDamage: 18000,
        totalTokens: 10,
        boss: "TervigonLeviathan",
        set: 0,
        tier: 0,
        startedOn: 1742984513,
    },
    {
        username: "testUser22",
        totalDamage: 63000, // sum of two runs in sets 1 & 2
        totalTokens: 20,
        boss: "HiveTyrantLeviathan",
        set: 1,
        tier: 0,
        startedOn: 1742984574,
    },
    {
        username: "testUser24",
        totalDamage: 91135,
        totalTokens: 25,
        boss: "ScreamerKiller",
        set: 3,
        tier: 0,
        startedOn: 1742985806,
    },
    {
        username: "testUser32",
        totalDamage: 27800,
        totalTokens: 12,
        boss: "ScreamerKiller",
        set: 3,
        tier: 0,
        startedOn: 1742986285,
    },
];

export const MemberStatsPerSeasonFixture: MemberStatsPerSeason[] = [
    {
        username: "Alpha",
        totalDamage: 10000,
        totalTokens: 5,
        minDmg: 1000,
        maxDmg: 3000,
        boss: "BossA",
        set: 1,
        tier: 0,
        startedOn: 123456,
        distribution: {
            multihit: 2,
            mech: 1,
            psyker: 1,
            other: 1,
            multihitDamage: 4000,
            mechDamage: 2000,
            psykerDamage: 3000,
            otherDamage: 1000,
        },
    },
    {
        username: "Bravo",
        totalDamage: 20000,
        totalTokens: 10,
        minDmg: 1500,
        maxDmg: 4000,
        boss: "BossB",
        set: 2,
        tier: 1,
        startedOn: 654321,
        distribution: {
            multihit: 3,
            mech: 2,
            psyker: 2,
            other: 3,
            multihitDamage: 8000,
            mechDamage: 4000,
            psykerDamage: 5000,
            otherDamage: 3000,
        },
    },
    {
        username: "",
        totalDamage: 0,
        totalTokens: 0,
        minDmg: 0,
        maxDmg: 0,
        boss: "BossC",
        set: 3,
        tier: 2,
        startedOn: 111111,
        distribution: {
            multihit: 0,
            mech: 0,
            psyker: 0,
            other: 0,
            multihitDamage: 0,
            mechDamage: 0,
            psykerDamage: 0,
            otherDamage: 0,
        },
    },
];
