import { DamageType, EncounterType, Rarity } from "@/models/enums";
import type { GuildRaidResult, Raid } from "@/models/types";
import type { MemberStatsPerSeason } from "@/commands/guild-raid/memberStatsBySeason";

export const RaidResultFixture: Raid[] = [
    {
        userId: "735d8c45-bac6-4770-a7e8-7f0adb0358c1",
        tier: 4,
        set: 0,
        encounterIndex: 2,
        remainingHp: 154613,
        maxHp: 350000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss2AdmecManipulus",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 195387,
        damageType: DamageType.BATTLE,
        startedOn: 1750314154,
        completedOn: 1750314243,
        heroDetails: [
            {
                unitId: "astraCreed",
                power: 131325,
            },
            {
                unitId: "astraYarrick",
                power: 326572,
            },
            {
                unitId: "blackPossession",
                power: 194393,
            },
            {
                unitId: "tauMarksman",
                power: 206215,
            },
            {
                unitId: "adeptCelestine",
                power: 159721,
            },
        ],
        machineOfWarDetails: {
            unitId: "tyranBiovore",
            power: 5572,
        },
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "ead18151-3b4d-4ac8-8e9c-a62d92d369d3",
        tier: 4,
        set: 0,
        encounterIndex: 1,
        remainingHp: 241782,
        maxHp: 300000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss1AdmecMarshall",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 58218,
        damageType: DamageType.BATTLE,
        startedOn: 1750314392,
        completedOn: 1750314552,
        heroDetails: [
            {
                unitId: "tyranNeurothrope",
                power: 111544,
            },
            {
                unitId: "ultraTitus",
                power: 70290,
            },
            {
                unitId: "orksWarboss",
                power: 67740,
            },
            {
                unitId: "orksRuntherd",
                power: 78837,
            },
            {
                unitId: "adeptMorvenn",
                power: 188201,
            },
        ],
        machineOfWarDetails: {
            unitId: "blackForgefiend",
            power: 922,
        },
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "2e336d0c-2504-4277-b22a-9c7bf76a2c37",
        tier: 4,
        set: 0,
        encounterIndex: 2,
        remainingHp: 143988,
        maxHp: 350000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss2AdmecManipulus",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 10625,
        damageType: DamageType.BOMB,
        startedOn: 1750314606,
        completedOn: 1750314606,
        heroDetails: [],
        machineOfWarDetails: null,
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "957b7e49-e319-4813-9f15-d957a6922a3c",
        tier: 4,
        set: 0,
        encounterIndex: 2,
        remainingHp: 133541,
        maxHp: 350000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss2AdmecManipulus",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 10447,
        damageType: DamageType.BOMB,
        startedOn: 1750314866,
        completedOn: 1750314866,
        heroDetails: [],
        machineOfWarDetails: null,
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "7a3cf298-b39e-49fd-849a-7553bdbe58c7",
        tier: 4,
        set: 0,
        encounterIndex: 2,
        remainingHp: 120509,
        maxHp: 350000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss2AdmecManipulus",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 13032,
        damageType: DamageType.BOMB,
        startedOn: 1750315061,
        completedOn: 1750315061,
        heroDetails: [],
        machineOfWarDetails: null,
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "7a3cf298-b39e-49fd-849a-7553bdbe58c7",
        tier: 4,
        set: 0,
        encounterIndex: 1,
        remainingHp: 45095,
        maxHp: 300000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss1AdmecMarshall",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 196687,
        damageType: DamageType.BATTLE,
        startedOn: 1750315090,
        completedOn: 1750315296,
        heroDetails: [
            {
                unitId: "orksRuntherd",
                power: 140946,
            },
            {
                unitId: "spaceBlackmane",
                power: 158652,
            },
            {
                unitId: "orksWarboss",
                power: 120965,
            },
            {
                unitId: "eldarFarseer",
                power: 214604,
            },
            {
                unitId: "eldarAutarch",
                power: 96892,
            },
        ],
        machineOfWarDetails: {
            unitId: "tyranBiovore",
            power: 794,
        },
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "55aefce2-e186-44ab-8532-82732e36f232",
        tier: 4,
        set: 0,
        encounterIndex: 1,
        remainingHp: 33424,
        maxHp: 300000,
        encounterType: EncounterType.SIDE_BOSS,
        unitId: "GuildBoss10MiniBoss1AdmecMarshall",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 11671,
        damageType: DamageType.BOMB,
        startedOn: 1750316864,
        completedOn: 1750316864,
        heroDetails: [],
        machineOfWarDetails: null,
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
    {
        userId: "55aefce2-e186-44ab-8532-82732e36f232",
        tier: 4,
        set: 0,
        encounterIndex: 0,
        remainingHp: 4238881,
        maxHp: 5000000,
        encounterType: EncounterType.BOSS,
        unitId: "GuildBoss10Boss1AdmecBelisarius",
        type: "Belisarius",
        rarity: Rarity.LEGENDARY,
        damageDealt: 761119,
        damageType: DamageType.BATTLE,
        startedOn: 1750316881,
        completedOn: 1750318958,
        heroDetails: [
            {
                unitId: "spaceBlackmane",
                power: 511288,
            },
            {
                unitId: "eldarFarseer",
                power: 421678,
            },
            {
                unitId: "worldKharn",
                power: 534662,
            },
            {
                unitId: "orksWarboss",
                power: 354190,
            },
            {
                unitId: "orksRuntherd",
                power: 390248,
            },
        ],
        machineOfWarDetails: {
            unitId: "astraOrdnanceBattery",
            power: 218211,
        },
        globalConfigHash: "34e9c937e23efbb6e4a3eca6f45f7c4d",
    },
];

export const GuildRaidResultFixture: GuildRaidResult[] = [
    {
        username: "testUser1",
        totalDamage: 18000,
        totalTokens: 10,
        boss: "TervigonLeviathan",
        set: 0,
        tier: 0,
        startedOn: 1742984513,
        bombCount: 0,
    },
    {
        username: "testUser22",
        totalDamage: 63000, // sum of two runs in sets 1 & 2
        totalTokens: 20,
        boss: "HiveTyrantLeviathan",
        set: 1,
        tier: 0,
        startedOn: 1742984574,
        bombCount: 0,
    },
    {
        username: "testUser24",
        totalDamage: 91135,
        totalTokens: 25,
        boss: "ScreamerKiller",
        set: 3,
        tier: 0,
        startedOn: 1742985806,
        bombCount: 0,
    },
    {
        username: "testUser32",
        totalDamage: 27800,
        totalTokens: 12,
        boss: "ScreamerKiller",
        set: 3,
        tier: 0,
        startedOn: 1742986285,
        bombCount: 0,
    },
];

export const MemberStatsPerSeasonFixture: MemberStatsPerSeason[] = [
    {
        username: "Alpha",
        totalDamage: 10000,
        totalTokens: 5,
        minDmg: 1000,
        maxDmg: 3000,
        boss: "BossA",
        set: 1,
        tier: 0,
        startedOn: 123456,
        distribution: {
            multihit: 2,
            mech: 1,
            psyker: 1,
            other: 1,
            multihitDamage: 4000,
            mechDamage: 2000,
            psykerDamage: 3000,
            otherDamage: 1000,
        },
        bombCount: 0,
    },
    {
        username: "Bravo",
        totalDamage: 20000,
        totalTokens: 10,
        minDmg: 1500,
        maxDmg: 4000,
        boss: "BossB",
        set: 2,
        tier: 1,
        startedOn: 654321,
        distribution: {
            multihit: 3,
            mech: 2,
            psyker: 2,
            other: 3,
            multihitDamage: 8000,
            mechDamage: 4000,
            psykerDamage: 5000,
            otherDamage: 3000,
        },
        bombCount: 0,
    },
    {
        username: "",
        totalDamage: 0,
        totalTokens: 0,
        minDmg: 0,
        maxDmg: 0,
        boss: "BossC",
        set: 3,
        tier: 2,
        startedOn: 111111,
        distribution: {
            multihit: 0,
            mech: 0,
            psyker: 0,
            other: 0,
            multihitDamage: 0,
            mechDamage: 0,
            psykerDamage: 0,
            otherDamage: 0,
        },
        bombCount: 0,
    },
];
