// This file now exports a dictionary for quick character lookups by id.
// Each entry contains only the id and name of the character.
export const characters = {
    Roswitha: { id: "adeptCanoness", name: "Roswitha" },
    Celestine: { id: "adeptCelestine", name: "Celestine" },
    Isabella: { id: "adeptHospitaller", name: "Isabella" },
    MorvennVahl: { id: "adeptMorvenn", name: "Morvenn Vahl" },
    Vindicta: { id: "adeptRetributor", name: "Vindicta" },
    SyGex: { id: "admecDestroyer", name: "Sy-gex" },
    Vitruvius: { id: "admecDominus", name: "Vitruvius" },
    Actus: { id: "admecManipulus", name: "Actus" },
    TanGida: { id: "admecMarshall", name: "Tan Gi'da" },
    ExitorRho: { id: "admecRuststalker", name: "Exitor-Rho" },
    Kut: { id: "astraBullgryn", name: "Kut" },
    Creed: { id: "astraCreed", name: "Creed" },
    Dreir: { id: "astraDreir", name: "Dreir" },
    Thaddeus: { id: "astraOrdnance", name: "Thaddeus" },
    Sibyll: { id: "astraPrimarisPsy", name: "Sibyll" },
    Yarrick: { id: "astraYarrick", name: "Yarrick" },
    Abaddon: { id: "blackAbaddon", name: "Abaddon" },
    Haarken: { id: "blackHaarken", name: "Haarken" },
    Volk: { id: "blackObliterator", name: "Volk" },
    Archimatos: { id: "blackPossession", name: "Archimatos" },
    Angrax: { id: "blackTerminator", name: "Angrax" },
    Dante: { id: "bloodDante", name: "Dante" },
    Lucien: { id: "bloodDeathCompany", name: "Lucien" },
    Mataneo: { id: "bloodIntercessor", name: "Mataneo" },
    Mephiston: { id: "bloodMephiston", name: "Mephiston" },
    Nicodemus: { id: "bloodSanguinary", name: "Nicodemus" },
    Atlacoya: { id: "custoAtlacoya", name: "Atlacoya" },
    Kariyan: { id: "custoBladeChampion", name: "Kariyan" },
    Trajann: { id: "custoTrajann", name: "Trajann" },
    Aesoth: { id: "custoVexilusPraetor", name: "Aesoth" },
    Asmodai: { id: "darkaAsmodai", name: "Asmodai" },
    Azrael: { id: "darkaAzrael", name: "Azrael" },
    Forcas: { id: "darkaCompanion", name: "Forcas" },
    Sarquael: { id: "darkaHellblaster", name: "Sarquael" },
    Baraqiel: { id: "darkaTerminator", name: "Baraqiel" },
    Corrodius: { id: "deathBlightbringer", name: "Corrodius" },
    Maladus: { id: "deathBlightlord", name: "Maladus" },
    Pestillian: { id: "deathPutrifier", name: "Pestillian" },
    Nauseous: { id: "deathRotbone", name: "Nauseous" },
    Typhus: { id: "deathTyphus", name: "Typhus" },
    Aethana: { id: "eldarAutarch", name: "Aethana" },
    Eldryon: { id: "eldarFarseer", name: "Eldryon" },
    JainZar: { id: "eldarJainZar", name: "Jain Zar" },
    MauganRa: { id: "eldarMauganRa", name: "Maugan Ra" },
    Calandis: { id: "eldarRanger", name: "Calandis" },
    Adamatar: { id: "emperKakophonist", name: "Adamatar" },
    Lucius: { id: "emperLucius", name: "Lucius" },
    Shiron: { id: "emperNoiseMarine", name: "Shiron" },
    Hollan: { id: "genesBiophagus", name: "Hollan" },
    Judh: { id: "genesKelermorph", name: "Judh" },
    Xybia: { id: "genesMagus", name: "Xybia" },
    Patermine: { id: "genesPatriarch", name: "The Patermine" },
    Isaak: { id: "genesPrimus", name: "Isaak" },
    Imospekh: { id: "necroDestroyer", name: "Imospekh" },
    Anuphet: { id: "necroOverlord", name: "Anuphet" },
    Thutmose: { id: "necroPlasmancer", name: "Thutmose" },
    AlephNull: { id: "necroSpyder", name: "Aleph-Null" },
    Makhotep: { id: "necroWarden", name: "Makhotep" },
    Gibbascrapz: { id: "orksBigMek", name: "Gibbascrapz" },
    Snappawrecka: { id: "orksKillaKan", name: "Snappawrecka" },
    Tanksmasha: { id: "orksNob", name: "Tanksmasha" },
    Snotflogga: { id: "orksRuntherd", name: "Snotflogga" },
    Gulgortz: { id: "orksWarboss", name: "Gulgortz" },
    Ragnar: { id: "spaceBlackmane", name: "Ragnar" },
    Tjark: { id: "spaceHound", name: "Tjark" },
    Arjac: { id: "spaceRockfist", name: "Arjac" },
    Njal: { id: "spaceStormcaller", name: "Njal" },
    Ulf: { id: "spaceWulfen", name: "Ulf" },
    AunShi: { id: "tauAunShi", name: "Aun'Shi" },
    Revas: { id: "tauCrisis", name: "Re'vas" },
    Darkstrider: { id: "tauDarkstrider", name: "Darkstrider" },
    Shosyl: { id: "tauMarksman", name: "Sho'syl" },
    Shadowsun: { id: "tauShadowsun", name: "Shadowsun" },
    Burchard: { id: "templAggressor", name: "Burchard" },
    Thoread: { id: "templAncient", name: "Thoread" },
    Jaeger: { id: "templChampion", name: "Jaeger" },
    Helbrecht: { id: "templHelbrecht", name: "Helbrecht" },
    Godswyl: { id: "templSwordBrother", name: "Godswyl" },
    Ahriman: { id: "thousAhriman", name: "Ahriman" },
    Abraxas: { id: "thousInfernalMaster", name: "Abraxas" },
    Thaumachus: { id: "thousSorcerer", name: "Thaumachus" },
    Toth: { id: "thousTerminator", name: "Toth" },
    Yazaghor: { id: "thousTzaangor", name: "Yazaghor" },
    Deathleaper: { id: "tyranDeathleaper", name: "Deathleaper" },
    Neurothrope: { id: "tyranNeurothrope", name: "Neurothrope" },
    Parasite: { id: "tyranParasite", name: "Parasite of Mortrex" },
    TyrantGuard: { id: "tyranTyrantGuard", name: "Tyrant Guard" },
    WingedPrime: { id: "tyranWingedPrime", name: "Winged Prime" },
    Incisus: { id: "ultraApothecary", name: "Incisus" },
    Calgar: { id: "ultraCalgar", name: "Calgar" },
    Certus: { id: "ultraEliminatorSgt", name: "Certus" },
    Bellator: { id: "ultraInceptorSgt", name: "Bellator" },
    Tigurius: { id: "ultraTigurius", name: "Tigurius" },
    Titus: { id: "ultraTitus", name: "Titus" },
    Azkor: { id: "worldEightbound", name: "Azkor" },
    Tarvakh: { id: "worldExecutions", name: "Tarvakh" },
    Macer: { id: "worldJakhal", name: "Macer" },
    Kharn: { id: "worldKharn", name: "Kharn" },
    Wrask: { id: "worldTerminator", name: "Wrask" },
};
