name: bun-test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            DB_NAME: my_database_test
            DB_USER: test_user
            DB_PWD: secret_password
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.5
                  node-version: 22.14.0

            - name: Install dependencies
              run: bun install

            - name: Print Bun and Node versions
              run: |
                  bun --version
                  node --version
            - name: Run tests with verbose output
              run: bun test; echo $?
